TARGET=rtt_desktop_test
OBJS=recvkeys.o sendkeys.o desktop.o

# CFLAGS=-m32 -L. -DTODO_WAKEUP_TEXTSHOW_PROCESS
CFLAGS=-m64 -DTODO_WAKEUP_TEXTSHOW_PROCESS

CFLAGS+=-ggdb3

all: tags $(TARGET)

clean:
	rm -f $(TARGET) *.o *.obj

anew: clean all

.c.o:
	gcc $(CFLAGS) -I/usr/include -I../../../include -c -o $@ $<

$(TARGET): $(OBJS)
	gcc $(CFLAGS) -o $@ $(OBJS) -lncurses

tags:
	ctags *.c

rtp-setup-pipe:
	mknod rtp-setup-pipe p
