/* TLV320AIC20/21/24/25/20K/24K codec driver
 *
 * The name "codec" is generally used for sound I/O chips that take a
 * realtime stream of samples and map send them to speakers; and that
 * do the opposite for microphone input.
 *
 * This driver has a generic part, described here, and a lower part
 * that actually gets the generated byte patterns to and from the chip,
 * which fits better in the actual phone implementation and/or in the
 * DSP/CPU chip driver.
 *
 * The assumption made in this driver is that there is a single unit
 * of this codec, and that its outputs are used as prescribed in the
 * datasheet for headset in/out, handset in/out and handsfree in/out
 * inasfar as these facilities are configured on the target phone in
 * HAVE_xxx variables.
 *
 * From: Rick van Rein <rick@openfortress.nl>
 */


/* Setup the sound channel to use: SOUND_NONE, _HANDSET, _HEADSET,
 * _SPEAKER and _LINE.  When set to SOUND_NONE, the chip is in setup
 * in configuration programming mode; in any other modes, it is setup
 * in continuous data transfer mode.
 */
void bottom_soundchannel (soundchannel_t sch) {
	//TODO//
}

/* Setup the communication with the codec, initialise the chip
 */
void tls320aic2x_setup_sound (void) {
	// TODO: Setup codec communications
	bottom_soundchannel (SOUND_NONE);
}
